[package]
name = "actix-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7"
actix-web = "4"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", features = ["runtime-async-std", "postgres"] }
