services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: todo-postgres
    restart: on-failure
    environment:
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_DB: root_db
      POSTGRES_USER: root_usr
      POSTGRES_PASSWORD: root_pwd
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 10s
      retries: 5

  sveltekit:
    profiles:
      - prod
    build:
      context: ./sveltekit-ui
    container_name: todo-sveltekit
    restart: on-failure
    depends_on:
      - postgres

  actix:
    profiles:
      - prod
    build:
      context: actix-backend
    container_name: todo-actix
    restart: on-failure

  nginx-prod:
    profiles:
      - prod
    build:
      context: nginx/prod
    container_name: todo-nginx-prod
    restart: on-failure
    depends_on:
      - sveltekit
      - actix
    ports:
      - "649:649"

  nginx-dev:
    profiles:
      - dev
    build:
      context: nginx/dev
    container_name: todo-nginx-dev
    restart: on-failure
    ports:
      - "649:649"
